context:
  version: "3.0.0"

package:
  name: eleventy
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@11ty/eleventy/-/eleventy-${{ version }}.tgz
  sha256: 821cd03bbaecf7dd657db6d20e3373e62fc30d78c44828b1334672294f924ec1

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - eleventy --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A simpler site generator. Transforms a directory of templates (of varying types) into HTML.
  homepage: https://github.com/11ty/eleventy
  repository: https://github.com/11ty/eleventy

extra:
  recipe-maintainers:
    - danielnachun
