context:
  version: "3.1.5"

package:
  name: eleventy
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@11ty/eleventy/-/eleventy-${{ version }}.tgz
  sha256: 65941649a92338aad8021fc0d0df1954b632f31299579f3e0ac72ef2a20a70d4

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - eleventy --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A simpler site generator. Transforms a directory of templates (of varying types) into HTML.
  homepage: https://github.com/11ty/eleventy
  repository: https://github.com/11ty/eleventy

extra:
  recipe-maintainers:
    - danielnachun
